chore: defining a place for project terminology
CMS-Enterprise/sbom-harbor pull request #76
Opened 2023-05-02 15:48 UTC by qtpeters

## Summary

Added some Rustdoc that establishes the beginning of a glossary in Harbcore.

### Added

Rustrdoc in the file core/src/lib.rs that will serve as a glossary of terms in SBOM Harbor

## How to test

1. Position a console at the root of the SBOM Harbor repository.
2. Run `cargo doc --open`
3. Your browser should open with the documentation loaded.
4. Verify that a section named `Terminology`exists and there are some terms defined.

2023-05-02 16:29 UTC, sbolel requested changes
minor spelling/grammar suggestions

2023-05-02 16:29 UTC, sbolel commented on core/src/lib.rs
> +//! - **Report**: in this context, a report is a Json document. Machine readable, but with text so humans can read it as well.
```suggestion
//! - **Report**: in this context, a report is a JSON document. Machine-readable, but with text so humans can read it as well.
```

2023-05-02 16:29 UTC, sbolel commented on core/src/lib.rs
> +//! - **Transitive Dependency**: A library that one of a given **Package**’s library needs to function.
```suggestion
//! - **Transitive Dependency**: A library that one of a given **Package**’s libraries needs to function.
```

2023-05-02 20:42 UTC, sbolel submitted a review, later dismissed
👍

2023-05-03 08:47 UTC, DerekStrickland approved these changes
Nice work!

2023-05-03 10:17 UTC, sbolel approved these changes

2023-05-04 01:07 UTC, DerekStrickland approved these changes
👍

2023-05-08 15:40 UTC, merged